{"name": "test_get_customer_info_with_wrong_data", "status": "failed", "statusDetails": {"message": "AssertionError: Expected 400 Bad Request\nassert 401 == 400\n +  where 401 = <Response [401]>.status_code", "trace": "self = <tests.api_test.TestApi object at 0x000001C5B796BDD0>\n\n    @allure.description(\"Test get customer info with wrong credentials\")\n    def test_get_customer_info_with_wrong_data(self):\n        url = f\"{self.base_url}/customers/me\"\n        headers = {\n            **self.common_headers,\n            \"Authorization\": f\"Bearer {\"12\"}\",\n        }\n        response = ApiRequests.get(url, headers=headers)\n>       assert response.status_code == 400, \"Expected 400 Bad Request\"\nE       AssertionError: Expected 400 Bad Request\nE       assert 401 == 400\nE        +  where 401 = <Response [401]>.status_code\n\napi_test.py:104: AssertionError"}, "description": "Test get customer info with wrong credentials", "attachments": [{"name": "[GET] request", "source": "4f6eb299-902b-465d-a1ba-439cd507b614-attachment.json", "type": "application/json"}, {"name": "response [401]", "source": "7f3a3d29-721e-42cd-8a77-38a50aacefb5-attachment.json", "type": "application/json"}], "start": 1708895091176, "stop": 1708895092473, "uuid": "233e2b21-3bd8-45ff-9630-ddee6436cc2c", "historyId": "b43116f1e4190a65f39884dda2463a77", "testCaseId": "b43116f1e4190a65f39884dda2463a77", "fullName": "api_test.TestApi#test_get_customer_info_with_wrong_data", "labels": [{"name": "feature", "value": "API Tests"}, {"name": "story", "value": "Customer Management"}, {"name": "tag", "value": "api"}, {"name": "tag", "value": "xdist_group(name='serial')"}, {"name": "suite", "value": "api_test"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "LAPTOP-EV98OK4E"}, {"name": "thread", "value": "20112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api_test"}]}