{"name": "test_create_customer", "status": "failed", "statusDetails": {"message": "AssertionError: Failed to create customer: {\"message\":\"A customer with the same email address already exists in an associated website.\"}\nassert 400 == 200\n +  where 400 = <Response [400]>.status_code", "trace": "self = <tests.api_test.TestApi object at 0x00000248A2999C70>\n\n    def test_create_customer(self):\n        url = f\"{self.base_url}/customers\"\n        response = ApiRequests.post(url, json=self.customer_payload, headers=self.common_headers)\n>       assert response.status_code == 200, f\"Failed to create customer: {response.text}\"\nE       AssertionError: Failed to create customer: {\"message\":\"A customer with the same email address already exists in an associated website.\"}\nE       assert 400 == 200\nE        +  where 400 = <Response [400]>.status_code\n\napi_test.py:69: AssertionError"}, "attachments": [{"name": "[POST] request", "source": "e38d5c43-795e-4ffd-a709-3639a65e18e6-attachment.json", "type": "application/json"}, {"name": "response [400]", "source": "161990b0-8153-4a89-b3c0-332518141304-attachment.json", "type": "application/json"}], "start": 1708859254409, "stop": 1708859256064, "uuid": "54d3b413-aece-4e45-ba80-8b76210ed14a", "historyId": "1689073ee40887eadd63d72aac5cf654", "testCaseId": "1689073ee40887eadd63d72aac5cf654", "fullName": "api_test.TestApi#test_create_customer", "labels": [{"name": "tag", "value": "api"}, {"name": "suite", "value": "api_test"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "LAPTOP-EV98OK4E"}, {"name": "thread", "value": "22344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api_test"}]}